version: '3.3'

services:
  btm-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - configs/dev.env
    volumes:
      - ./dist:/app/dist
    network_mode: "host"
    restart: unless-stopped
