// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"BTM-backend/configs"
	"BTM-backend/internal/domain"
	"BTM-backend/internal/repo/impl"
	"BTM-backend/third_party/db"
)

// Injectors from wire.go:

func NewRepo() (domain.Repository, error) {
	gormDB := db.ConnectToDatabase()
	config := configs.NewConfigs()
	repository := impl.NewRepository(gormDB, config)
	return repository, nil
}
