package domain

type BTMRole struct {
	ID       uint   `json:"id"`
	RoleName string `json:"role_name"`
	RoleDesc string `json:"role_desc"`
	RoleRaw  string `json:"role_raw"`
}

const DefaultRoleRaw = `[{"id":"permissionBar","path":"/permission","meta":{"roles":["admin"]},"children":[{"id":"permission","path":"index","name":"權限設定","meta":{"title":"權限設定","icon":"lock","roles":["admin"]}}]},{"id":"userBar","path":"/user","redirect":"/user/page","name":"User","meta":{"title":"會員總覽","icon":"user","roles":["admin"]},"children":[{"id":"transaction","path":"/transaction","name":"交易記錄","meta":{"title":"交易記錄","icon":"el-icon-s-order","roles":["admin"],"noCache":true}}]},{"id":"auditBar","path":"/audit","redirect":"/audit/page","name":"審核紀錄","meta":{"title":"審核紀錄","icon":"list","roles":["admin"]},"children":[],"hidden":true},{"id":"txBar","path":"/tx","redirect":"/tx/page","name":"交易監控","meta":{"title":"交易監控","icon":"list","roles":["admin"]},"children":[],"hidden":true},{"id":"riskBar","path":"/risk_control","redirect":"/risk_control/page","name":"風控","meta":{"title":"風控","icon":"component","roles":["admin"]},"children":[{"id":"whitelist","path":"whitelist","name":"風控白名單","meta":{"title":"風控白名單","icon":"eye-open","roles":["admin"]}},{"id":"whitelistView","path":"whitelist/view","name":"風控白名單限額編輯","hidden":true,"meta":{"title":"風控白名單限額編輯","roles":["admin"]}},{"id":"graylist","path":"graylist","name":"風控灰名單","meta":{"title":"風控灰名單","icon":"eye","roles":["admin"]}},{"id":"graylistView","path":"graylist/view","name":"風控灰名單限額編輯","hidden":true,"meta":{"title":"風控灰名單限額編輯","roles":["admin"]}},{"id":"blacklist","path":"blacklist","name":"風控黑名單","meta":{"title":"風控黑名單","icon":"el-icon-s-release","roles":["admin"]}},{"id":"blacklistView","path":"blacklist/view","name":"風控黑名單限額編輯","hidden":true,"meta":{"title":"風控黑名單限額編輯","roles":["admin"]}}]},{"id":"reviewBar","path":"/review","redirect":"/review/cibs","name":"審核作業","meta":{"title":"審核作業","icon":"list","roles":["admin"]},"children":[{"id":"cibs","path":"cibs","name":"告誡名單","meta":{"title":"告誡名單","icon":"el-icon-warning","roles":["admin"],"noCache":true}},{"id":"cibsUpload","path":"cibs/upload","name":"上傳告誡名單","hidden":true,"meta":{"title":"上傳告誡名單","icon":"el-icon-upload","roles":["admin"],"noCache":true}},{"id":"addresslist","path":"addresslist","name":"綁定地址","meta":{"title":"綁定地址","icon":"education","roles":["admin"],"noCache":true}},{"id":"addresslistView","path":"/addresslist/view","name":"綁定地址編輯","hidden":true,"meta":{"title":"綁定地址編輯","roles":["admin"],"noCache":true}}]},{"path":"*","redirect":"/404","hidden":true}]`
