package domain

type BTMRole struct {
	ID       uint   `json:"id"`
	RoleName string `json:"role_name"`
	RoleDesc string `json:"role_desc"`
	Role     int64  `json:"role"`
	RoleRaw  string `json:"role_raw"`
}

const DefaultRoleRaw = `[{"path":"/permission","redirect":"/permission/page","alwaysShow":true,"name":"Permission","meta":{"title":"Permission","icon":"lock","roles":["admin"]},"children":[{"path":"role","name":"RolePermission","meta":{"title":"Role Permission","roles":["admin"]}}]},{"path":"/user","redirect":"/user/page","alwaysShow":true,"name":"User","meta":{"title":"會員總覽","icon":"user","roles":["admin","editor"]},"children":[{"path":"addresslist","name":"綁定地址","meta":{"title":"綁定地址","icon":"education","roles":["admin","editor"],"noCache":true}},{"path":"/addresslist/view","name":"綁定地址編輯","hidden":true,"meta":{"title":"綁定地址編輯","roles":["admin","editor"],"noCache":true}},{"path":"/transaction","name":"交易記錄","meta":{"title":"交易記錄","icon":"el-icon-s-order","roles":["admin","editor"],"noCache":true}}]},{"path":"/audit","redirect":"/audit/page","alwaysShow":true,"name":"審核紀錄","meta":{"title":"審核紀錄","icon":"list","roles":["admin","editor"]},"children":[],"hidden":true},{"path":"/tx","redirect":"/tx/page","alwaysShow":true,"name":"交易監控","meta":{"title":"交易監控","icon":"list","roles":["admin","editor"]},"children":[],"hidden":true},{"path":"/risk_control","redirect":"/risk_control/page","alwaysShow":true,"name":"風控","meta":{"title":"風控","icon":"list","roles":["admin","editor"]},"children":[{"path":"whitelist","name":"風控白名單","meta":{"title":"風控白名單","icon":"eye-open"}},{"path":"whitelist/view","name":"風控白名單限額編輯","hidden":true,"meta":{"title":"風控白名單限額編輯"}},{"path":"graylist","name":"風控灰名單","meta":{"title":"風控灰名單","icon":"eye","roles":["admin","editor"]}},{"path":"graylist/view","name":"風控灰名單限額編輯","hidden":true,"meta":{"title":"風控灰名單限額編輯"}},{"path":"blacklist","name":"風控黑名單","meta":{"title":"風控黑名單","icon":"el-icon-s-release","roles":["admin","editor"]}},{"path":"blacklist/view","name":"風控黑名單限額編輯","hidden":true,"meta":{"title":"風控黑名單限額編輯"}}]},{"path":"/cibs","name":"告誡名單","meta":{"title":"告誡名單","icon":"el-icon-warning","roles":["admin","editor"]},"children":[{"path":"index","name":"告誡名單","meta":{"title":"告誡名單","icon":"el-icon-warning","roles":["admin","editor"],"noCache":true}},{"path":"upload","name":"上傳告誡名單","meta":{"title":"上傳告誡名單","icon":"el-icon-upload","roles":["admin","editor"],"noCache":true}}]},{"path":"*","redirect":"/404","hidden":true}]`
